service: serverless-rest-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Querry
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  createExpense:
    handler: controllers/expenses/create.handler
    events:
      - http:
          path: expenses
          method: post
          cors: true
  deleteExpense:
    handler: controllers/expenses/delete.handler
    events:
      - http:
          path: expenses/{id}
          method: delete
          cors: true
  listExpense:
    handler: controllers/expenses/list.handler
    events:
      - http:
          path: expenses/list
          method: post #TODO: Use get and fix route
          cors: true
  getExpense:
    handler: controllers/expenses/get.handler
    events:
      - http:
          path: expenses/get
          method: post #TODO: Use Get, fix route
          cors: true
  # createComment:
  #   handler: apis/comments/create.create
  #   events:
  #     - http:
  #         path: comments
  #         method: post
  #         cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    ExpensesDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete #Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "expenses"
